-- Distribuidora Avinova - esquema PostgreSQL para Neon/Render
-- No elimina tablas existentes ni recrea Better Auth.
-- Ejecutar una sola vez sobre la base configurada en DATABASE_URL.

CREATE TABLE IF NOT EXISTS disponibilidad_semanal (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semana_inicio date NOT NULL,
  semana_fin date NOT NULL,
  genero varchar(10) NOT NULL CHECK (genero IN ('macho', 'hembra')),
  cajas_totales integer NOT NULL DEFAULT 0 CHECK (cajas_totales >= 0),
  cajas_reservadas integer NOT NULL DEFAULT 0 CHECK (cajas_reservadas >= 0 AND cajas_reservadas <= cajas_totales),
  cajas_disponibles integer NOT NULL DEFAULT 0 CHECK (cajas_disponibles >= 0 AND cajas_disponibles <= cajas_totales),
  estado varchar(10) NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta', 'cerrada', 'agotada')),
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_actualizacion timestamptz NOT NULL DEFAULT now(),
  UNIQUE (semana_inicio, semana_fin, genero),
  CHECK (semana_fin >= semana_inicio)
);

CREATE TABLE IF NOT EXISTS entregas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id integer NOT NULL UNIQUE REFERENCES reservations(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  direccion varchar(255) NOT NULL,
  detalles_entrega text,
  latitud numeric(10,7),
  longitud numeric(10,7),
  persona_recibe varchar(150) NOT NULL,
  telefono_recibe varchar(30) NOT NULL,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_actualizacion timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mensajes_contacto (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id text REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE SET NULL,
  nombre varchar(150) NOT NULL,
  correo varchar(190) NOT NULL,
  asunto varchar(200) NOT NULL,
  mensaje text NOT NULL,
  estado varchar(10) NOT NULL DEFAULT 'nuevo' CHECK (estado IN ('nuevo', 'leido', 'atendido', 'archivado')),
  fecha_envio timestamptz NOT NULL DEFAULT now(),
  fecha_atencion timestamptz
);

CREATE TABLE IF NOT EXISTS notificaciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id text NOT NULL,
  reserva_id integer REFERENCES reservations(id) ON UPDATE CASCADE ON DELETE SET NULL,
  titulo varchar(150) NOT NULL,
  contenido text NOT NULL,
  leida boolean NOT NULL DEFAULT false,
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS informacion_institucional (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave varchar(80) NOT NULL UNIQUE,
  titulo varchar(200) NOT NULL,
  contenido text NOT NULL,
  imagen varchar(255),
  estado varchar(10) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
  fecha_actualizacion timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auditoria_reservas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id integer NOT NULL REFERENCES reservations(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  usuario_id text REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE SET NULL,
  accion varchar(12) NOT NULL CHECK (accion IN ('creada', 'confirmada', 'cancelada', 'completada', 'rechazada', 'actualizada')),
  estado_anterior varchar(12),
  estado_nuevo varchar(12),
  observaciones text,
  fecha_accion timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_disponibilidad_semana ON disponibilidad_semanal (semana_inicio, semana_fin);
CREATE INDEX IF NOT EXISTS idx_disponibilidad_estado ON disponibilidad_semanal (estado);
CREATE INDEX IF NOT EXISTS idx_mensajes_estado ON mensajes_contacto (estado);
CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario ON notificaciones (usuario_id, leida);
CREATE INDEX IF NOT EXISTS idx_auditoria_reserva ON auditoria_reservas (reserva_id);

INSERT INTO disponibilidad_semanal (semana_inicio, semana_fin, genero, cajas_totales, cajas_disponibles)
VALUES
  ('2026-10-05', '2026-10-11', 'macho', 80, 80),
  ('2026-10-05', '2026-10-11', 'hembra', 80, 80),
  ('2026-10-12', '2026-10-18', 'macho', 100, 100),
  ('2026-10-12', '2026-10-18', 'hembra', 100, 100),
  ('2026-10-19', '2026-10-25', 'macho', 120, 120),
  ('2026-10-19', '2026-10-25', 'hembra', 120, 120)
ON CONFLICT (semana_inicio, semana_fin, genero) DO NOTHING;

INSERT INTO informacion_institucional (clave, titulo, contenido)
VALUES
  ('nombre_empresa', 'Distribuidora Avinova', 'Distribuidora Avinova conecta granjas y negocios con pollitos bebés de excelente calidad.'),
  ('mision', 'Nuestra misión', 'Brindar distribución responsable de pollitos bebés con asesoría cercana y atención personalizada.'),
  ('vision', 'Nuestra visión', 'Ser un aliado confiable para granjas y negocios avícolas.'),
  ('contacto', 'Información de contacto', 'Teléfono: (57) 320 513 5667 | Correo: avinova@correo.com'),
  ('horario', 'Horario de atención', 'Lunes a sábado, de 8:00 a.m. a 5:00 p.m.')
ON CONFLICT (clave) DO NOTHING;

-- La tabla reservations y las tablas user/session/account/verification
-- pertenecen a la aplicación y Better Auth. No se borran ni se duplican aquí.
-- Las reservas actuales usan userId, customerName, phone, email,
-- deliveryDate, quantity, status, notes, createdAt y updatedAt.

SELECT 'Esquema Avinova aplicado correctamente' AS resultado;
